// scripts/legislation-scraper.js
//
// Full replacement file: scrapes legislation data and fills schema,
// now wired to load enacted-fallback.json for becameLaw counts.

const fs = require('fs');
const path = require('path');
const axios = require('axios');

// Load enacted fallback JSON generated by generate-enacted-fallback.js
const ENACTED_FALLBACK = JSON.parse(
  fs.readFileSync(path.join(__dirname, '../public/enacted-fallback.json'), 'utf-8')
);

// Load senators roster (bootstrap already created this)
const senators = JSON.parse(
  fs.readFileSync(path.join(__dirname, '../public/legislators-current.json'), 'utf-8')
);

// Output file
const outputPath = path.join(__dirname, '../public/legislation-senators.json');

// Example function to fetch legislation data from Congress.gov API
async function fetchLegislation(bioguideId) {
  // Replace with your actual API calls / parsing logic
  // This is a placeholder to show structure
  return {
    sponsored: Math.floor(Math.random() * 50),   // replace with real data
    cosponsored: Math.floor(Math.random() * 100) // replace with real data
  };
}

(async () => {
  const results = [];

  for (const sen of senators) {
    const bioguideId = sen.id?.bioguide;
    if (!bioguideId) continue;

    // Get sponsored/cosponsored counts from Congress.gov
    const legisData = await fetchLegislation(bioguideId);

    // Attach becameLaw from fallback JSON
    const becameLawCount = ENACTED_FALLBACK[bioguideId] || 0;

    results.push({
      bioguideId,
      name: `${sen.name.first} ${sen.name.last}`,
      state: sen.terms?.[sen.terms.length - 1]?.state || '',
      party: sen.terms?.[sen.terms.length - 1]?.party || '',
      sponsored: legisData.sponsored,
      cosponsored: legisData.cosponsored,
      becameLaw: becameLawCount
    });
  }

  fs.writeFileSync(outputPath, JSON.stringify(results, null, 2));
  console.log(`Wrote ${results.length} senator records to ${outputPath}`);
})();
